# Generated by Django 5.0.2 on 2026-02-10 08:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('task', 'Task'), ('comment', 'Comment'), ('attachment', 'Attachment')], max_length=50)),
                ('entity_id', models.UUIDField()),
                ('local_version', models.JSONField()),
                ('server_version', models.JSONField()),
                ('local_vector_clock', models.JSONField()),
                ('server_vector_clock', models.JSONField()),
                ('conflict_reason', models.TextField(blank=True, null=True)),
                ('resolution_strategy', models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto_merge', 'Auto Merge'), ('local_wins', 'Local Wins'), ('server_wins', 'Server Wins')], max_length=50, null=True)),
                ('resolved_version', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='core.device')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conflicts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='conflicts_entity__c864d1_idx'), models.Index(fields=['user'], name='conflicts_user_id_abafec_idx'), models.Index(fields=['-created_at'], name='conflicts_created_2fe284_idx'), models.Index(fields=['resolved_at'], name='conflicts_resolve_ec66a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('conflict', 'Conflict')], max_length=50)),
                ('entities_pushed', models.IntegerField(default=0)),
                ('entities_pulled', models.IntegerField(default=0)),
                ('conflicts_detected', models.IntegerField(default=0)),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device'], name='sync_logs_device__7c063c_idx'), models.Index(fields=['user'], name='sync_logs_user_id_c3f134_idx'), models.Index(fields=['-created_at'], name='sync_logs_created_a9c4e8_idx'), models.Index(fields=['status'], name='sync_logs_status_e8f5ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tombstone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('task', 'Task'), ('comment', 'Comment'), ('attachment', 'Attachment')], max_length=50)),
                ('entity_id', models.UUIDField()),
                ('vector_clock', models.JSONField()),
                ('entity_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tombstones', to=settings.AUTH_USER_MODEL)),
                ('deleted_from_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombstones', to='core.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tombstones', to='core.organization')),
            ],
            options={
                'db_table': 'tombstones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='tombstones_entity__950d6b_idx'), models.Index(fields=['organization'], name='tombstones_organiz_08c8e0_idx'), models.Index(fields=['-created_at'], name='tombstones_created_de4cd1_idx'), models.Index(fields=['expires_at'], name='tombstones_expires_3a8f77_idx')],
            },
        ),
    ]
