# Generated by Django 5.0.2 on 2026-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='resolution_strategy',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto_merge', 'Auto Merge'), ('local_wins', 'Local Wins'), ('server_wins', 'Server Wins'), ('auto_resolved', 'Auto Resolved')], max_length=50, null=True),
        ),
    ]
